# Generated by Django 2.0.4 on 2018-09-16 12:23

from django.db import migrations, models
import django.db.models.deletion
import macTools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100, verbose_name='最新版本')),
                ('language', models.CharField(choices=[('CH', '中文'), ('EN', '英文')], help_text='工具语言', max_length=100, verbose_name='语言')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('file_size', models.CharField(max_length=100, verbose_name='文件大小')),
                ('drive_type', models.IntegerField(choices=[(1, '百度网盘'), (2, '360网盘'), (3, '115网盘')], default=1, help_text='网盘类型', verbose_name='网盘类型')),
                ('drive_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='网盘下载链接')),
                ('drive_pw', models.CharField(blank=True, max_length=100, null=True, verbose_name='网盘密码')),
            ],
            options={
                'verbose_name': '网盘链接',
                'verbose_name_plural': '网盘链接',
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to=macTools.models.upload_path_handler, verbose_name='展示图')),
                ('title', models.CharField(max_length=100, verbose_name='工具标题')),
                ('new_version', models.CharField(max_length=100, verbose_name='最新版本')),
                ('cate', models.IntegerField(choices=[(1, '应用软件'), (2, '媒体工具'), (3, '网络工具'), (4, '开发工具'), (5, '设计工具'), (6, '行业软件'), (7, '安全防护'), (8, '系统工具'), (9, '免费精品'), (10, '其他')], help_text='工具类别', verbose_name='工具类别')),
                ('tag', models.CharField(max_length=300, verbose_name='标签')),
                ('introduction', models.CharField(blank=True, max_length=300, null=True, verbose_name='工具简介')),
                ('content', models.TextField()),
                ('download_num', models.IntegerField(default=0, help_text='下载次数', verbose_name='下载次数')),
                ('looked_num', models.IntegerField(default=0, help_text='浏览量', verbose_name='浏览量')),
                ('active', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
                ('create_id', models.CharField(max_length=100, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('edit_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='修改人')),
                ('edit_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('delete_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='删除人')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
            ],
            options={
                'verbose_name': '工具详情',
                'verbose_name_plural': '工具列表',
            },
        ),
        migrations.AddField(
            model_name='historyversion',
            name='tools',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macTools.Tools', verbose_name='所属工具'),
        ),
    ]
