# Generated by Django 2.0.4 on 2018-09-30 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macTools', '0002_auto_20180927_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyversion',
            name='tools',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools_sys', to='macTools.Tools', verbose_name='所属工具'),
        ),
    ]
