# Generated by Django 2.0.4 on 2018-11-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designLists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='desgin',
            table=None,
        ),
    ]
