# Generated by Django 2.0.4 on 2018-11-27 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designLists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desgin',
            options={'verbose_name': '设计列表', 'verbose_name_plural': '设计列表'},
        ),
    ]
