# Generated by Django 2.0.4 on 2018-11-27 00:40

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import resources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_type', models.IntegerField(choices=[(1, '百度网盘'), (2, '360网盘'), (3, '115网盘')], default=1, help_text='网盘类型', verbose_name='网盘类型')),
                ('drive_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='网盘下载链接')),
                ('drive_pw', models.CharField(blank=True, max_length=100, null=True, verbose_name='网盘密码')),
            ],
            options={
                'verbose_name': '网盘链接',
                'verbose_name_plural': '网盘链接',
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='素材标题')),
                ('cate', models.IntegerField(choices=[(1, 'UI'), (2, '线性icon'), (3, '彩色icon'), (4, 'UI Kit'), (5, '写实'), (6, '插画'), (7, '电商'), (8, '交互'), (9, '报表'), (10, 'GIF'), (11, 'C4D'), (12, 'Mockup'), (13, '平面设计')], help_text='素材类别', verbose_name='素材类别')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('copyright', models.CharField(max_length=100, verbose_name='版权')),
                ('picture', models.ImageField(upload_to=resources.models.upload_path_handler, verbose_name='展示图')),
                ('introduction', models.CharField(blank=True, max_length=300, null=True, verbose_name='素材简介')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容\t')),
                ('tag', models.CharField(max_length=300, verbose_name='标签')),
                ('download_num', models.IntegerField(default=0, help_text='下载次数', verbose_name='下载次数')),
                ('looked_num', models.IntegerField(default=0, help_text='浏览量', verbose_name='浏览量')),
                ('file_type', models.CharField(default='sketch', max_length=100, verbose_name='文件类型')),
                ('download_address', models.FileField(upload_to=resources.models.upload_resource, verbose_name='下载链接')),
                ('active', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
                ('createman', models.CharField(max_length=100, verbose_name='创建人')),
                ('createtime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updateman', models.CharField(blank=True, max_length=100, null=True, verbose_name='修改人')),
                ('updatetime', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('deleteman', models.CharField(blank=True, max_length=100, null=True, verbose_name='删除人')),
                ('deletetime', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
            ],
            options={
                'verbose_name': '素材详情',
                'verbose_name_plural': '素材列表',
            },
        ),
        migrations.AddField(
            model_name='clouddrive',
            name='resources',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_drive', to='resources.Resources', verbose_name='所属素材'),
        ),
    ]
