# Generated by Django 2.0.4 on 2018-09-27 04:34

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20180829_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouddrive',
            name='drive_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='网盘下载链接'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='cate',
            field=models.IntegerField(choices=[(1, 'UI'), (2, '线性icon'), (3, '彩色icon'), (4, 'UI Kit'), (5, '写实'), (6, '插画'), (7, '电商'), (8, '交互'), (9, '报表'), (10, 'GIF'), (11, 'C4D'), (12, 'Mockup'), (13, '平面设计')], help_text='素材类别', verbose_name='素材类别'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容\t'),
        ),
    ]
