# Generated by Django 2.0.4 on 2018-09-28 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20180927_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouddrive',
            name='resources',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_drive', to='resources.Resources', verbose_name='所属素材'),
        ),
    ]
