# Generated by Django 2.0.4 on 2018-11-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20180928_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='tag',
            field=models.CharField(max_length=300, verbose_name='标签'),
        ),
    ]
