# Generated by Django 2.2.5 on 2021-05-26 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20180928_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='修改时间'),
            preserve_default=False,
        ),
    ]
