# Generated by Django 2.0.4 on 2018-09-27 04:34

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='cate',
            field=models.IntegerField(choices=[(1, '设计分享'), (2, '前端分享'), (3, '后端分享'), (4, '经验分享'), (5, '工具配置')], help_text='文章类别', verbose_name='文章类别'),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容\t'),
        ),
    ]
