# Generated by Django 2.0.4 on 2018-11-27 08:33

from django.db import migrations, models
import myDesign.models


class Migration(migrations.Migration):

    dependencies = [
        ('myDesign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designworks',
            name='picture',
            field=models.ImageField(max_length=300, upload_to=myDesign.models.DesignWorks.upload_path_handler, verbose_name='展示图'),
        ),
    ]
