# Generated by Django 2.0.4 on 2018-10-17 02:34

from django.db import migrations, models
import myLinks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection_net',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(max_length=300, upload_to=myLinks.models.upload_path_handler, verbose_name='链接ico')),
                ('net_name', models.CharField(max_length=100, verbose_name='网站名称')),
                ('link_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='网站链接')),
            ],
            options={
                'verbose_name': '收藏网站',
                'verbose_name_plural': '收藏网站',
            },
        ),
        migrations.CreateModel(
            name='Friends_net',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_name', models.CharField(max_length=100, verbose_name='网站名称')),
                ('link_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='网站链接')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
    ]
